### ISSUE TITLE
Implementar cálculos FCPST e FCPSTRetido

### ISSUE THREAD

**Issue by robertorp** [AutomacaoNet/MotorTributarioNet#11]
Conforme NF-e 4.00

**Comment by felixsevero** [comment]
Boa noite @robertorp, estou implementando a emissão de notas fiscais com o auxílio deste projeto. Para a emissão de NF-e 4.0 com CST=10, acredito que será necessário utilizar-se o vFCPST, entretanto me parece que isso ainda não está implementado, correto? Você ou outra pessoa está trabalhando nisso, ou eu poderia contribuir de alguma forma?

**Comment by robertorp** [comment]
Ainda não tem dentro dos icms
Mas se você olhar a classe FacadeCalculadoraTributacao
vai achar o calculo la dentro já. Oque falta e colocar o mesmo dentro dos CST

Se quiser fazer isso fique a sinta-se a vontade e eu fico imensamente grato =)

**Comment by felixsevero** [comment]
Bom dia, desculpe pela demora em responder, mas as coisas andaram meio corridas por aqui. Vou tentar colocar o cálculo do FCP dentro dos CSTs. Só para ficar claro, seriam os CSTs que encontram-se em MotorTributarioNet.Impostos.Csts? Se sim, seria apenas criar um novo campo nessas classes e utilizar o cálculo que já foi implementado em FacadeCalculadoraTributacao?
