### ISSUE TITLE
Novos Projetos

### ISSUE THREAD

**Issue by gui-abrantes** [AutomacaoNet/MotorTributarioNet#15]
Fala @robertorp , vi que tem esse perfil AutomacaoNet no GitHub, e existe esses dois projetos MotorTributarioNet e ProjetoAutomacaoNet.

Como que tá esse MotorTributario? Vc tá usando ele nas suas aplicações? Vi que tem um commit recente nele, ele tá ainda em fase de desenvolvimento? Sobre os cálculos tributários, a regra é sempre as mesmas, ou seja, só passar as variáveis e o calculo é sempre da mesma forma? Pq tenho alguns clientes, dentro do mesmo estado, que o contador às vezes "embirra" de calcular de uma forma e outro de outra forma, por isso q me surgiu a dúvida!

E esse ProjetoAutomacaoNet? Vi que vc tá refatorando o Zeus DFe.Net....vc pretende manter os dois? Que pé que tá esse projeto?

To com essas dúvidas, pq eu to com um projeto meu pessoal, e gostei muito da experiência em trabalhar colaborativamente, principalmente nessas coisas fiscais: NF-e, NFC-e... SPED, pois as SEFAZ muda constantemente, e compartilhar soluções entre vários desenvolvedores, ajuda em muito a dinâmica que o governo impõe! Pq tdo muda constantemente, portanto nesse projeto pessoal, pretendo pegar muito dessas soluções, pq daí as mudanças nas regras fica centralizado, e não fico fechado somente na minha pessoa.

**Comment by robertorp** [comment]
Opá tudo bom @gui-abrantes 
Sempre tive esse motortributario e sim uso em minha aplicação! 
ele esta sempre em desenvolvimento, ahh e tem mais, minha aplicação roda em uns 8 estados hoje com esse motor tributário, 
Eu digo para você o que digo para todos, não recomendo deixar de entender tributação por causa desse motor. 

E interessante usar ele porque todos colaboram, nos, nós ajudamos a agilizar o trabalho na parte que envolve o governo. E em até em ideias de desenvolvimento de telas rola as vezes. 

Sim o Zeus sempre vou manter ele. Uso também no meu projeto. 
O motor tributário uso ele no meu sistema para emissão de NF-e simples nacional pois so atendo o regime simples nacional hoje, mas ele esta preparado para Regime normal também.

uso ele para Emissão de CT-e/CT-e OS simples nacional/Regime normal também

E sempre procuro manter ele. Bem como o Zeus também. Por onde passo se utilizo um framework procuro ajudar, afinal estou usando também ne. Enfim você pode usar tranquilo. Se quiser me add no skype podemos trocar ideias. 

robertoalves18@hotmail.com

**Comment by robertorp** [comment]
ProjetoAutomacaoNet

E um projeto mais ambicioso que tenho mas esse vai levar um tempo para sair do papel/ideias é muito grande ele. Mas se sair do papel muita gente vai gostar.

**Comment by gui-abrantes** [comment]
Quem bom @robertorp, vou add seu contato no skype. Venho do VB.NET pq os sistemas legados aqui da empresa é VB.NET, mexo muito pouco em C#, por isso as vezes a minha cautela de ajudar mais nos projetos, rsrsrs!! Mas o que eu puder ajudar, só falar! Pq isso me interessa, e muito tb. rsrs
