### ISSUE TITLE
Erro no Flags CstPisCofins da Ultima Versão do Nuget (2.1.1)

### ISSUE THREAD

**Issue by Alexandre-Jamsoft** [AutomacaoNet/MotorTributarioNet#16]
A versão mais Recente disponível no Nuget Apresenta erro no Enum CstPisCofins Com Relação ao Cst01 que está representada pelo Código 99 ao invés do Código 01.

Obs.: A ultima versão do Commit já está com a Correção, falta atualizar a Packager no Nuget, 

Tem algum prazo para determinado para a atualização está disponível?

**Comment by robertorp** [comment]
Vou estar disponibilizando pouco depois do almoço.

**Comment by Alexandre-Jamsoft** [comment]
Obrigado!

**Comment by robertorp** [comment]
https://www.nuget.org/packages/MotorTributarioNet/2.1.2
publicado agora e somente aguardar a liberação do nuget.
