### ISSUE TITLE
Erro calculo ICMS

### ISSUE THREAD

**Issue by ThalisonSantos** [AutomacaoNet/MotorTributarioNet#17]
no método ICMS.calcula quando cst é 40 retorno uma exceção dizendo "não existe calculo" está certo é assim mesmo ?

**Comment by robertorp** [comment]
Sim, não tem calculo ai não precisa executar ele. 

editado:
http://tsdn.tecnospeed.com.br/base-de-conhecimento/post/cst-tributacao-do-icms-40-41-ou-50/p/8

40 = Isento

**Comment by ThalisonSantos** [comment]
@robertorp mas seria melhor se retornasse zero e não uma exceção

**Comment by robertorp** [comment]
Um caso a se analisar e pensar, porque o intuitivo da exception é

Você não sabe nada de impostos exemplo
O framework lança uma exception dizendo que não tem calculo.

Agora se o framework retorna 0
O que você faria? abriria uma issue aqui dizendo que o framework esta bugado? 

enfim.. e um caso a se analisar, qual a melhor abordagem para essa situação, porque nos temos que trabalhar de certa forma no qual o framework ajude quem use mesmo se quem use não tenha conhecimentos em tributação. Apesar de que e o que sempre digo, recomendo que todos aprendam tributação, mas sabemos que isso nem sempre acontece né.

**Comment by ThalisonSantos** [comment]
@robertorp é faz sentido, mas pensei que o difal fosse calculado para todos os produtos

**Comment by robertorp** [comment]
difal?

**Comment by ThalisonSantos** [comment]
partilha do icms

**Comment by robertorp** [comment]
Ah sim, não sei se difal e calculado para alguns produtos somente ou se é para todos. Vou pesquisar sobre o assunto e posto aqui.

**Comment by ThalisonSantos** [comment]
ok ficarei no aguardo
