### ISSUE TITLE
Erro calculo do fcp

### ISSUE THREAD

**Issue by ThalisonSantos** [AutomacaoNet/MotorTributarioNet#19]
quando o produto tem desconto o calculo do fcp esta fazendo com base no valor do produto sem desconto

**Comment by robertorp** [comment]
como assim? coloque para min um exemplo de parametros aqui e como deveria sair 
já viu que existe na biblioteca a opçaõ de desconto incondicional e condicional ne?

**Comment by ThalisonSantos** [comment]
@robertorp  não vi essa opção onde fica?

**Comment by robertorp** [comment]
Se você usa a Facade

![image](https://user-images.githubusercontent.com/10251705/43589954-3a0e20bc-9646-11e8-8702-8e07dc110f18.png)

Segundo parâmetro do construtor

**Comment by ThalisonSantos** [comment]
@robertorp eu não uso facade . eu herdo a sua classe iTributavelProduto passo os parâmetros e uso o método ResultadoTributação.Calcular()

**Comment by ThalisonSantos** [comment]
comecei a usar o facade valeu
