### ISSUE TITLE
Calcular Ibpt

### ISSUE THREAD

**Issue by ThalisonSantos** [AutomacaoNet/MotorTributarioNet#20]
o método calcular ibpt já tem as alíquotas embutidas ou acessa o webservice do ibpt para calcular?

**Comment by robertorp** [comment]
Dentro da `FacadeCalculadoraTributacao`

```
public IResultadoCalculoIbpt CalculaIbpt(IIbpt ibpt)
        {
            return new TributacaoIbpt(_tributavel, ibpt).Calcula();
        }
```

**Comment by ThalisonSantos** [comment]
@robertorp mas faz algum tipo de conexão com algum webservice ou a dll já tem alíquotas dos tributos?

**Comment by robertorp** [comment]
as aliquotas vc deve setar no objeto que implementar o IIbpt 
o calculo ele faz com base nos valores do produto e aliquotas

**Comment by ThalisonSantos** [comment]
no caso eu tenho que passar as alíquotas e método faz o calculo

**Comment by robertorp** [comment]
tem que passar os valores que tem na IIbpt 
existem testes unitários para ela aqui https://github.com/AutomacaoNet/MotorTributarioNet/blob/master/src/TestMotorTributarioNet/CalculoIbptTest.cs

**Comment by ThalisonSantos** [comment]
blz valeu @robertorp
