### ISSUE TITLE
Calculo da base do PIS e COFINS

### ISSUE THREAD

**Issue by WashingtonAutocom** [AutomacaoNet/MotorTributarioNet#22]
Olá pessoal.
Estou analisando a questão do calculo da base do PIS e COFINS depois de reparar que o valor de desconto está sendo somado na base de calculo, o que segundo relatado por um consultor contábil não deveria ocorrer no caso do desconto feito antes da emissão do documento fiscal e que altere o preço de venda do produto.

Verificando o processo do calculo, eu vi que ele está correto e inclusive já levando em consideração o tipo do desconto, porem eu reparei que por padrão e de forma fixa o tipo do desconto foi configurado como sendo "Condicional" o que acarretaria na soma do desconto na base de calculo em vez da subtração, seria esse ponto que acredito está acontecendo o erro pois desconto Condicional seria apenas para processo que é feito após a emissão do documento fiscal no momento de apuração de receita da empresa, portanto eu acho que o correto seria o tipo de desconto ser o Incondicional, pois basicamente no processo que é utilizado o Motor Tributário só existiria mesmo o desconto do tipo Incondicional.

Trecho onde no caso do PIS é atribuído fixamente o tipo de desconto Condicional como padrão.
![image](https://user-images.githubusercontent.com/65791820/145262519-692d0b52-1ca5-4563-8c4a-4caa9af54cd4.png)

Apenas como referencia sobre a questão dos tipos de desconto, deixo o trecho abaixo que foi retirado do link abaixo:
https://tributarionosbastidores.com.br/2020/11/receita-descontos-condicionais-nao-integram-a-base-dos-tributos-de-empresa-imobiliaria/

> “Os descontos incondicionais consideram-se parcelas redutoras do preço de vendas, quando constarem da nota fiscal de venda dos bens ou da fatura de serviços e não dependerem de evento posterior à emissão desses documentos; esses descontos não se incluem na receita bruta da pessoa jurídica vendedora e, do ponto de vista da pessoa jurídica adquirente dos bens ou serviços, constituem redutor do custo de aquisição, não configurando receita.

> Os descontos condicionais são aqueles que dependem de evento posterior à emissão da nota fiscal, usualmente, do pagamento da compra dentro de certo prazo, e configuram despesa financeira para o vendedor e receita financeira para o comprador.” (Solução de Consulta Cosit nº 34, de 21 de novembro de 2013).

O que você acha @robertorp, já que você que mantem o projeto ultimamente, se eu não estiver equivocado eu posso fazer essa pequena correção e abrir o PullRequest, ou o que acharem melhor.

**Comment by WashingtonAutocom** [comment]
Para adiantar o processo eu já criei o PullRequest #23.
Mais vamos discutindo e se necessário eu faço os ajustes, a modificação que eu fiz eu coloquei como parâmetro o tipo de desconto, mais pode ser modificado somente onde é declarado o tipo Condicional na chamada dos métodos.

E caso eu tenha feito algum procedimento errado para criar a issue ou o PR por favor avisem para que possa corrigir e fazer certo da próxima vez.

**Comment by robertorp** [comment]
Irei analisar amanhã já depois das 16:00 da tarde.

**Comment by WashingtonAutocom** [comment]
> Irei analisar amanhã já depois das 16:00 da tarde.

Show de bola, vou aproveitar e criar alguns testes hoje.

**Comment by WashingtonAutocom** [comment]
@robertorp.
Eu adicionei vários testes para ajudar na validação do desconto incondicional.

Para ajudar na sua analise, nos testes não ocorria o erro porque no construtor do "FacadeCalculadoraTributacao" já é informado por padrão o tipo de de desconto incondicional.
![image](https://user-images.githubusercontent.com/65791820/145434916-65ca8148-005d-463d-b761-7dc98aa2f851.png)

Então como exemplo no teste que poderia ser afetado que era o "CalculaDifalJuntoComFcp" não ocorria mesmo a diferença da base porque no construtor era setado o tipo de desconto incondicional.

Agora quando era utilizado fora dos testes, com o uso da classe "ResultadoTributacao.Calcular()" era retornado a diferença devido ao problema que relatei do Tipo de Desconto Condicional setado manualmente.

Espero ter ajudado em alguma coisa, estou a total disposição ok.

**Comment by robertorp** [comment]
Estou analisando é pesquisando também sobre o assunto , mas aparentemente o que você disse , faz sentido total. Mas irei verificar mais antes de aceitar ok?

**Comment by WashingtonAutocom** [comment]
Perfeito. 
Isso mesmo, é bom conferir e ter certeza, eu também pesquisei bastante sobre esse ponto pensando que o calculo estava errado, mais na verdade não, o processo do calculo está tudo certo na verdade tá muito bom, apenas era o tipo de desconto como parâmetro padrão que estava trocado.

No Pull Request eu achei melhor deixar a possibilidade de passar o tipo do desconto por parâmetro caso exista alguma exceção, assim atende todos o casos, mesmo tendo chegado na ideia que não teria desconto condicional na emissão do documento fiscal, porem o Motor Tributário poderia ser utilizado para calcular tributos para outros objetivos.

**Comment by robertorp** [comment]
Foi feito o merge das alterações , obrigado
