### ISSUE TITLE
Duvida no metodo resultado tributação

### ISSUE THREAD

**Issue by ThalisonSantos** [AutomacaoNet/MotorTributarioNet#8]
é preciso informar todos os campos?

**Comment by robertorp** [comment]
Não, você somente informa oque precisa ou oque tem disponível e a lib ira calcular.
Se você olhar os testes de unidade ira verificar que nos testes não são informados todos os campos.

**Comment by ThalisonSantos** [comment]
@robertorp  eu fiz dessa forma mas retornou tudo zero

produto.Cst = (Cst)Convert.ToInt32(NfItem.CST.Substring(1,2));
            produto.Desconto = (decimal)NfItem.TOTALDESC;
            produto.Documento = Documento.NFe;
            produto.Frete = (decimal)NfItem.VLRFRETE;
            produto.IsServico = false;
            produto.OutrasDespesas = (decimal)NfItem.VLROUTRAS;
            produto.PercentualCofins = (decimal)estoque.COFINS;
            produto.PercentualDifalInterestadual = 80m;
            produto.PercentualFcp = 1m;
            produto.PercentualIcms = (decimal)NfItem.ALIQICMS;
            produto.PercentualPis = (decimal)estoque.PIS;
            produto.PercentualReducao = (decimal)estoque.ICMSRBCALC;
            produto.QuantidadeProduto = NfItem.QTDE;
            produto.Seguro = Convert.ToDecimal(NfItem.VLSEG);
            produto.ValorProduto = NfItem.VLRUNIT;
            
            ResultadoTributacao tributacao = new ResultadoTributacao(produto,(Crt)crt,(TipoOperacao)tipoOperacao,(TipoPessoa)tipoPessoa);

**Comment by robertorp** [comment]
Me passe os valores setados e qual o método utilizado para estar analisando e criando testes para essa classe.

**Comment by ThalisonSantos** [comment]
@robertorp  está indo assim:
produto.Cst = 00;
produto.Desconto = 0;
produto.Documento = Documento.NFe;
produto.Frete = 0;
produto.IsServico = false;
produto.OutrasDespesas = 0;
produto.PercentualCofins = 15;
produto.PercentualDifalInterestadual = 80m;
produto.PercentualFcp = 1m;
produto.PercentualIcms = 18;
produto.PercentualPis = 5;
produto.PercentualReducao = 0;
produto.QuantidadeProduto = 9;
produto.Seguro = 0;
produto.ValorProduto =23,00;

**Comment by robertorp** [comment]
ResultadoTributacao tributacao = new ResultadoTributacao(produto,(Crt)crt,(TipoOperacao)tipoOperacao,(TipoPessoa)tipoPessoa);

esses parâmetros são quais?

**Comment by robertorp** [comment]
```
[TestClass]
    public class ResultadoTributacaoTest
    {
        [TestMethod]
        public void TestaCalculoCST00()
        {
            var produto = new Produto();

            produto.Cst = MotorTributarioNet.Flags.Cst.Cst00;
            produto.Desconto = 0;
            produto.Documento = Documento.NFe;
            produto.Frete = 0;
            produto.IsServico = false;
            produto.OutrasDespesas = 0;
            produto.PercentualCofins = 15;
            produto.PercentualDifalInterestadual = 80m;
            produto.PercentualFcp = 1m;
            produto.PercentualIcms = 18;
            produto.PercentualPis = 5;
            produto.PercentualReducao = 0;
            produto.QuantidadeProduto = 9;
            produto.Seguro = 0;
            produto.ValorProduto = 23;

            ResultadoTributacao tributacao = new ResultadoTributacao(produto, Crt.RegimeNormal, TipoOperacao.OperacaoInterna, TipoPessoa.Juridica);

            var resultado = tributacao.Calcular();
            Assert.AreEqual(37.26m, resultado.ValorIcms);
        }
        
    }
```

Fiz esse teste e funcionou perfeitamente.

**Comment by robertorp** [comment]
Se utilizar a dll mais atual deletei a classe Produto que vem no motorTributario a mesma pode ser substituida por uma classe qualquer sua no sistema que implemente a interface
"ITributavelProduto" a interface representa um Produto

**Comment by ThalisonSantos** [comment]
@robertorp no método passei os seguintes parâmetros (produto, Crt.RegimeNormal, TipoOperacao.OperacaoInterestadual, TipoPessoa.Juridica).
estou usando via nuget

**Comment by ThalisonSantos** [comment]
@robertorp  consegui fazer funcionar mas notei que apesar de passar as alíquotas do DIFAL e FCP ambos retornaram zero
Edit: Não calculou pq estava passando operação interna, com operação interestadual calculou normalmente

**Comment by robertorp** [comment]
@ThalisonSantos, na lib você deve informar o percentualDifalInterna e difalinterestadual 
existe um teste unitário CalculoDifalFcpTest 
veja o exemplo lá 

```
[TestMethod]
        public void CalculaDifalJuntoComFcp()
        {
            var produto = new Produto
            {
                ValorProduto = 845.00m,
                QuantidadeProduto = 1.000m,
                Frete = 35.00m,
                OutrasDespesas = 80.00m,
                Desconto = 10.00m,
                ValorIpi = 50.00m,
                PercentualFcp = 02.00m,
                PercentualDifalInterna = 18.00m,
                PercentualDifalInterestadual = 12.00m
            };

            var facade = new FacadeCalculadoraTributacao(produto);

            var resultadoCalculoDifal = facade.CalculaDifalFcp();

            Assert.AreEqual(1000.00m, resultadoCalculoDifal.BaseCalculo);
            Assert.AreEqual(20.00m, resultadoCalculoDifal.Fcp);
            Assert.AreEqual(60.00m, resultadoCalculoDifal.Difal);
            Assert.AreEqual(12.00m, resultadoCalculoDifal.ValorIcmsOrigem);
            Assert.AreEqual(48.00m, resultadoCalculoDifal.ValorIcmsDestino);
            Assert.AreEqual("Valores totais do ICMS interstadual: DIFAL da UF destino 48,00 + FCP 20,00; DIFAL da UF Origem 12,00",
                resultadoCalculoDifal.GetObservacao(new DadosMensagemDifal(decimal.Round(resultadoCalculoDifal.Fcp, 2), 
                    decimal.Round(resultadoCalculoDifal.ValorIcmsDestino, 2),
                    decimal.Round(resultadoCalculoDifal.ValorIcmsOrigem, 2))));

            Assert.AreEqual("Valores totais do ICMS interstadual: DIFAL da UF destino 48,00 + FCP 20,00; DIFAL da UF Origem 12,00",
                ResultadoCalculoDifal.GetObservacaoDifal(new DadosMensagemDifal(decimal.Round(resultadoCalculoDifal.Fcp, 2),
                    decimal.Round(resultadoCalculoDifal.ValorIcmsDestino, 2),
                    decimal.Round(resultadoCalculoDifal.ValorIcmsOrigem, 2))));
        }
```

o percentualDifalInterna = 18.00
e o percentual interestadual = 12% 

agora o percentual de origem e destino a lib se encarrega de colocar sozinha
no caso o ano e de 2018 a legislação é PercentualOrigem 20% e PercentualDestino 80%

PercentualDifalInterna coloca ela que ira funcionar

edit2: reorganizado resposta

**Comment by ThalisonSantos** [comment]
@robertorp  já funcionou blz já consegui calcular, a questão ficou somente o fcp que só calcula quando a operação é interestadual. aproveitando vc tem alguma tabela com as alíquotas fcp por estado ou por ncm?

**Comment by robertorp** [comment]
@ThalisonSantos  tenho não, no meu sistema o cliente tem que digitar num parâmetro de UF. Vou corrigir isso que você reportou, quando terminar de corrigir deixo aqui o aviso blz?

**Comment by ThalisonSantos** [comment]
@robertorp valeu muito obrigado

**Comment by robertorp** [comment]
@ThalisonSantos  Fiz os ajustes necessários agora independente do que for ele calculará o FCP 
As 16 horas da tarde do dia de hoje (18/03/2018) estará disponível no nuget.
