### ISSUE TITLE
e-Financeira

### ISSUE THREAD

**Issue by willianas1** [AutomacaoNet/MotorTributarioNet#9]
Bom dia Pessoal, 

Sei que não é o foco do projeto, mais alguém já desenvolveu/desenvolve a solução e-Financeira da Receita Federal? 

http://sped.rfb.gov.br/projeto/show/1179

**Comment by robertorp** [comment]
Pergunta fora do escopo do projeto.
A mesma foi respondida no repositório do Zeus.
